import Head from "next/head";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillYoutube,
} from "react-icons/ai";
import Link from "next/link";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState, useRef } from "react";
import deved from "../public/dev-ed-wave.jpg";
import Image from "next/image";
import web1 from "../public/ddd.png";
import web2 from "../public/eee.jpg";
import web3 from "../public/sddefault.jpg";
import web4 from "../public/2066861_96b5_7.jpg";
import web5 from "../public/ecom.webp";
import web6 from "../public/port.png";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  // Refs for scrolling
  const projectsRef = useRef(null);
  const contactRef = useRef(null);

  const scrollToSection = (ref) => {
    ref.current?.scrollIntoView({ behavior: "smooth" });
  };

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Nahom Mitiku</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <h1 className="font-burtons text-xl">developed by NM</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className="cursor-pointer text-2xl"
                />
              </li>
              <li>
                <button
                  onClick={() => scrollToSection(projectsRef)}
                  className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
                >
                  Projects
                </button>
              </li>
              <li>
                <button
                  onClick={() => scrollToSection(contactRef)}
                  className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
                >
                  Contact Me
                </button>
              </li>
            </ul>
          </nav>

          <div className="text-center p-10 py-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">
              Nahom Mitiku
            </h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
              Computer and Electrical Engineer.
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
              An Electrical and Computer Engineer with a deep passion for both hardware and software. I specialize in building full-stack web applications alongside embedded systems and CPU design. With a strong focus on creating scalable, efficient web solutions, I seamlessly integrate my skills across the entire development process—from front-end user interfaces to back-end architecture.
            </p>
            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
              <Link href="https://x.com/NahomMitiku12">
                <AiFillTwitterCircle />
              </Link>
              <Link href="https://www.linkedin.com/in/nahom-mitiku-5bb642245/">
                <AiFillLinkedin />
              </Link>
              <Link href="https://www.youtube.com/channel/yourchannel">
                <AiFillYoutube />
              </Link>
              </div>
            <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-96 md:w-96">
              <Image src={deved} layout="fill" objectFit="cover" alt="Developer Image" />
            </div>
          </div>
        </section>

        {/* Projects Section */}
        <section ref={projectsRef} className="py-10">
          <div>
            <h3 className="text-3xl py-1 dark:text-white">Projects</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Since the beginning of my journey as a developer and in other hardware projects, I have done different projects. Here are some of them.
            </p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            {/* Project 1 */}
            <div className="basis-1/3 flex-1 relative group shadow-lg">
              <h3 className="text-3xl py-1 dark:text-white">Roha Coffe Export</h3>
              <div className="relative h-0 pb-[56.25%] overflow-hidden rounded-lg">
                <Image
                  className="absolute inset-0 w-full h-full object-cover transition-transform duration-300 ease-in-out group-hover:scale-105"
                  layout="fill"
                  src={web1}
                  alt="Project 1"
                />
              </div>
              <div className="absolute inset-0 flex items-center justify-center opacity-0 group-hover:opacity-100 transition-opacity duration-300 ease-in-out">
                <div className="flex space-x-4">
                  <Link href="https://github.com/nahom124578/roha_coffee.git">
                    <button className="bg-gray-800 text-white px-4 py-2 rounded-lg shadow-lg transition-transform transform hover:scale-105">
                      View Code
                    </button>
                  </Link>
                  <Link href="https://roha.dev.awura.tech/">
                    <button className="bg-blue-600 text-white px-4 py-2 rounded-lg shadow-lg transition-transform transform hover:scale-105">
                      Live Demo
                    </button>
                  </Link>
                </div>
              </div>
            </div>

            {/* Project 2 */}
            <div className="basis-1/3 flex-1 relative group shadow-lg">
              <h3 className="text-3xl py-1 dark:text-white">Ecommerce for Cloth & Shoes</h3>
              <div className="relative h-0 pb-[56.25%] overflow-hidden rounded-lg">
                <Image
                  className="absolute inset-0 w-full h-full object-cover transition-transform duration-300 ease-in-out group-hover:scale-105"
                  layout="fill"
                  src={web2}
                  alt="Project 2"
                />
              </div>
              <div className="absolute inset-0 flex items-center justify-center opacity-0 group-hover:opacity-100 transition-opacity duration-300 ease-in-out">
                <div className="flex space-x-4">
                  <Link href="https://github.com/nahom124578/mygit.git">
                    <button className="bg-gray-800 text-white px-4 py-2 rounded-lg shadow-lg transition-transform transform hover:scale-105">
                      View Code
                    </button>
                  </Link>
                  <Link href="https://your-live-demo-url.com">
                    <button className="bg-blue-600 text-white px-4 py-2 rounded-lg shadow-lg transition-transform transform hover:scale-105">
                      Live Demo
                    </button>
                  </Link>
                </div>
              </div>
            </div>

            {/* Project 3 */}
            <div className="basis-1/3 flex-1 relative group shadow-lg">
              <h3 className="text-3xl py-1 dark:text-white">Design Engineering System</h3>
              <div className="relative h-0 pb-[56.25%] overflow-hidden rounded-lg">
                <Image
                  className="absolute inset-0 w-full h-full object-cover transition-transform duration-300 ease-in-out group-hover:scale-105"
                  layout="fill"
                  src={web3}
                  alt="Project 3"
                />
              </div>
              <div className="absolute inset-0 flex items-center justify-center opacity-0 group-hover:opacity-100 transition-opacity duration-300 ease-in-out">
                <div className="flex space-x-4">
                  <Link href="https://github.com/nahom124578/mygit.git">
                    <button className="bg-gray-800 text-white px-4 py-2 rounded-lg shadow-lg transition-transform transform hover:scale-105">
                      View Code
                    </button>
                  </Link>
                  <Link href="https://your-live-demo-url.com">
                    <button className="bg-blue-600 text-white px-4 py-2 rounded-lg shadow-lg transition-transform transform hover:scale-105">
                      Live Demo
                    </button>
                  </Link>
                </div>
              </div>
            </div>

            {/* Project 4 */}
            <div className="basis-1/3 flex-1 relative group shadow-lg">
              <h3 className="text-3xl py-1 dark:text-white">Engineering Mini Project</h3>
              <div className="relative h-0 pb-[56.25%] overflow-hidden rounded-lg">
                <Image
                  className="absolute inset-0 w-full h-full object-cover transition-transform duration-300 ease-in-out group-hover:scale-105"
                  layout="fill"
                  src={web4}
                  alt="Project 4"
                />
              </div>
              <div className="absolute inset-0 flex items-center justify-center opacity-0 group-hover:opacity-100 transition-opacity duration-300 ease-in-out">
                <div className="flex space-x-4">
                  <Link href="https://github.com/nahom124578/mygit.git">
                    <button className="bg-gray-800 text-white px-4 py-2 rounded-lg shadow-lg transition-transform transform hover:scale-105">
                      View Code
                    </button>
                  </Link>
                  <Link href="https://your-live-demo-url.com">
                    <button className="bg-blue-600 text-white px-4 py-2 rounded-lg shadow-lg transition-transform transform hover:scale-105">
                      Live Demo
                    </button>
                  </Link>
                </div>
              </div>
            </div>

            {/* Project 5 */}
            <div className="basis-1/3 flex-1 relative group shadow-lg">
              <h3 className="text-3xl py-1 dark:text-white">Online Shopping System</h3>
              <div className="relative h-0 pb-[56.25%] overflow-hidden rounded-lg">
                <Image
                  className="absolute inset-0 w-full h-full object-cover transition-transform duration-300 ease-in-out group-hover:scale-105"
                  layout="fill"
                  src={web5}
                  alt="Project 5"
                />
              </div>
              <div className="absolute inset-0 flex items-center justify-center opacity-0 group-hover:opacity-100 transition-opacity duration-300 ease-in-out">
                <div className="flex space-x-4">
                  <Link href="https://github.com/nahom124578/mygit.git">
                    <button className="bg-gray-800 text-white px-4 py-2 rounded-lg shadow-lg transition-transform transform hover:scale-105">
                      View Code
                    </button>
                  </Link>
                  <Link href="https://your-live-demo-url.com">
                    <button className="bg-blue-600 text-white px-4 py-2 rounded-lg shadow-lg transition-transform transform hover:scale-105">
                      Live Demo
                    </button>
                  </Link>
                </div>
              </div>
            </div>

            {/* Project 6 */}
            <div className="basis-1/3 flex-1 relative group shadow-lg">
              <h3 className="text-3xl py-1 dark:text-white">Portfolio</h3>
              <div className="relative h-0 pb-[56.25%] overflow-hidden rounded-lg">
                <Image
                  className="absolute inset-0 w-full h-full object-cover transition-transform duration-300 ease-in-out group-hover:scale-105"
                  layout="fill"
                  src={web6}
                  alt="Project 6"
                />
              </div>
              <div className="absolute inset-0 flex items-center justify-center opacity-0 group-hover:opacity-100 transition-opacity duration-300 ease-in-out">
                <div className="flex space-x-4">
                  <Link href="https://github.com/nahom124578/mygit.git">
                    <button className="bg-gray-800 text-white px-4 py-2 rounded-lg shadow-lg transition-transform transform hover:scale-105">
                      View Code
                    </button>
                  </Link>
                  <Link href="https://your-live-demo-url.com">
                    <button className="bg-blue-600 text-white px-4 py-2 rounded-lg shadow-lg transition-transform transform hover:scale-105">
                      Live Demo
                    </button>
                  </Link>
                </div>
              </div>
            </div>
          </div>
        </section>

        {/* Contact Me Section */}
         <section ref={contactRef}>
          <div className="bg-gradient-to-b from-teal-300 p-10 rounded-lg shadow-lg">
            <h3 className="text-4xl py-1 text-black">Contact Me</h3>
            <p className="text-lg text-black py-2">
              You can contact me via email or phone for any inquiries. I am also active on social media.
            </p>
            <div className="flex flex-col items-start space-y-4 mt-5">
              {/* Email */}
              <p className="text-black">
                Email:{" "}
                <a
                  href="mailto:nahom.mitiku@aait.edu.et"
                  className="text-yellow-500 underline hover:text-red-500"
                >
                  nahom.mitiku@aait.edu.et
                </a>
              </p>

              {/* Phone */}
              <p className="text-black">Phone: <span className="text-yellow-500">+251976166204</span></p>

              {/* Social Media */}
              <div className="flex space-x-4">
                <a
                  href="https://x.com/NahomMitiku12"
                  className="text-black hover:text-gray-300"
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  <AiFillTwitterCircle size={40} />
                </a>
                <a
                  href="https://www.linkedin.com/in/nahom-mitiku-5bb642245/"
                  className="text-black hover:text-gray-300"
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  <AiFillLinkedin size={40} />
                </a>
                <a
                  href="https://www.youtube.com/channel/yourchannel"
                  className="text-black hover:text-gray-300"
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  <AiFillYoutube size={40} />
                </a>
              </div>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
