import Head from "next/head";
import resume from "./resume";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillYoutube,
} from "react-icons/ai";
import Link from "next/link";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
import deved from "../public/dev-ed-wave.jpg";
import code from "../public/code.png";
import design from "../public/design.png";
import consulting from "../public/consulting.png";
import Image from "next/image";
import web1 from "../public/system-accessed-by-doctors-fingerprint-260nw-2291512001.webp";
import web2 from "../public/eee.jpg";
import web3 from "../public/sddefault.jpg";
import web4 from "../public/2066861_96b5_7.jpg";
import web5 from "../public/ecom.webp";
import web6 from "../public/port.png";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Nahom Mitiku</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <h1 className="font-burtons text-xl">developed by NM</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className="cursor-pointer text-2xl"
                />
              </li>
              <li>
                <Link href="/resume">
                  <h1 className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8">
                    Resume
                  </h1>
                </Link>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 py-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">
              Nahom Mitiku
            </h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
              Computer and Electrical Engineer.
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
              An Electrical and Computer Engineer with a passion for both hardware and software. I specialize in building full-stack web applications, embedded systems, and CPU design.
            </p>
            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
              <AiFillTwitterCircle />
              <AiFillLinkedin />
              <AiFillYoutube />
            </div>
            <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-96 md:w-96">
              <Image src={deved} layout="fill" objectFit="cover" alt="Developer Image" />
            </div>
          </div>
        </section>

        {/* Projects Section */}
        <section className="py-10">
          <h3 className="text-3xl py-1 dark:text-white">Projects</h3>
          <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
            Since the beginning of my journey as a developer and in other hardware projects, I have worked on various projects.
          </p>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            {/* Repeated Project Cards */}
            {/* Add your project cards here (as per previous code) */}
          </div>
        </section>

        {/* Contact Form Section */}
        <section id="contact" className="py-10">
          <h3 className="text-3xl py-1 dark:text-white">Contact Me</h3>
          <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
            Feel free to reach out through the form below or directly via phone or email.
          </p>

          <div className="max-w-md mx-auto bg-white dark:bg-gray-800 p-8 shadow-lg rounded-lg">
            <form action="#" method="POST" className="space-y-4">
              <div>
                <label htmlFor="name" className="block text-sm font-medium text-gray-700 dark:text-gray-200">
                  Name
                </label>
                <input
                  type="text"
                  id="name"
                  name="name"
                  className="mt-1 block w-full px-3 py-2 bg-gray-100 dark:bg-gray-700 border border-gray-300 dark:border-gray-600 rounded-md shadow-sm"
                  required
                />
              </div>
              <div>
                <label htmlFor="email" className="block text-sm font-medium text-gray-700 dark:text-gray-200">
                  Email
                </label>
                <input
                  type="email"
                  id="email"
                  name="email"
                  className="mt-1 block w-full px-3 py-2 bg-gray-100 dark:bg-gray-700 border border-gray-300 dark:border-gray-600 rounded-md shadow-sm"
                  required
                />
              </div>
              <div>
                <label htmlFor="message" className="block text-sm font-medium text-gray-700 dark:text-gray-200">
                  Message
                </label>
                <textarea
                  id="message"
                  name="message"
                  rows="4"
                  className="mt-1 block w-full px-3 py-2 bg-gray-100 dark:bg-gray-700 border border-gray-300 dark:border-gray-600 rounded-md shadow-sm"
                  required
                />
              </div>
              <button
                type="submit"
                className="w-full bg-teal-600 text-white py-2 rounded-md shadow-md hover:bg-teal-700 transition"
              >
                Send Message
              </button>
            </form>

            <div className="mt-8">
              <p className="text-gray-700 dark:text-gray-200">
                Or contact me directly:
              </p>
              <p className="text-gray-800 dark:text-gray-300">Phone: +251976166204</p>
              <p className="text-gray-800 dark:text-gray-300">Email: nahom.mitiku@aait.edu.et</p>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
